export const SITE = {
  website: "https://blog.158247.xyz",
  author: "Kayden",
  profile: "https://blog.158247.xyz/about",
  desc: "技术笔记、项目记录与工程实践分享",
  title: "Kayden's Blog",
  ogImage: "og.png",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "编辑页面",
    url: "https://github.com/example/repo/edit/main/",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
